export const images = [
  {
    src: '/shed.jpeg',
    alt: 'Shed by Orion Remodeling & Handyman',
    title: 'Shed',
    className: 'aspect-square',
  },
  {
    src: '/kitchen.jpeg',
    alt: 'Kitchen by Orion Remodeling & Handyman',
    title: 'Kitchen Renovation',
    className: 'aspect-[2/1] md:col-span-2',
  },
  {
    src: '/b-reno-1.jpeg',
    alt: 'Bathroom Renovation',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/b-reno-2.jpeg',
    alt: 'Bathroom Renovation',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/b-reno-3.jpeg',
    alt: 'Bathroom Renovation',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/b-reno-4.jpeg',
    alt: 'Bathroom Renovation',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/b-reno-4-2.jpeg',
    alt: 'Bathroom Renovation',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/b-reno-5.jpeg',
    alt: 'Bathroom Renovation',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/f-reno-1.jpeg',
    alt: 'Fence Renovation',
    title: 'Fence Renovation',
    className: 'aspect-square md:aspect-[4/1] md:col-span-3',
  },
  {
    src: '/f-reno-1-2.jpeg',
    alt: 'Fence Renovation',
    title: 'Fence Renovation',
    className: 'aspect-square',
  },
  {
    src: '/f-reno-1-3.jpeg',
    alt: 'Fence Renovation',
    title: 'Fence Renovation',
    className: 'aspect-square',
  },
  {
    src: '/f-reno-1-4.jpeg',
    alt: 'Fence Renovation',
    title: 'Fence Renovation',
    className: 'aspect-square',
  },
  {
    src: '/l-reno-1.jpeg',
    alt: 'Laundry Room Renovation',
    title: 'Laundry Room Renovation',
    className: 'aspect-square',
  },
  {
    src: '/lr-reno-1.jpeg',
    alt: 'Living Room Renovation',
    title: 'Living Room Renovation',
    className: 'aspect-square',
  },
  {
    src: '/reno-before-1.jpeg',
    alt: 'Room Renovation - Before',
    title: 'Room Renovation - Before',
    className: 'aspect-square',
  },
  {
    src: '/reno-after-1.jpeg',
    alt: 'Room Renovation - After',
    title: 'Room Renovation - After',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-1.jpeg',
    alt: 'Staircase Renovation',
    title: 'Staircase Renovation',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-1-2.jpeg',
    alt: 'Staircase Renovation',
    title: 'Staircase Renovation',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-2-before.jpeg',
    alt: 'Staircase Renovation - Before',
    title: 'Staircase Renovation - Before',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-2.jpeg',
    alt: 'Staircase Renovation - After',
    title: 'Staircase Renovation - After',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-2-3.jpeg',
    alt: 'Staircase Renovation - After',
    title: 'Staircase Renovation - After',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-3.jpeg',
    alt: 'Staircase Renovation',
    title: 'Staircase Renovation',
    className: 'aspect-square',
  },
  {
    src: '/renovation.jpeg',
    alt: 'Renovation by Orion Remodeling & Handyman',
    title: 'Living Room Renovation',
    className: 'aspect-[2/1] md:col-span-2',
  },
];
