export const images = [
  {
    src: '/shed.jpeg',
    alt: 'Custom backyard shed built by Orion Remodeling & Handyman',
    title: 'Shed',
    className: 'aspect-square',
  },
  {
    src: '/kitchen.jpeg',
    alt: 'Modern kitchen renovation with updated cabinets and countertops by Orion Remodeling & Handyman',
    title: 'Kitchen Renovation',
    className: 'aspect-[2/1] md:col-span-2',
  },
  {
    src: '/b-reno-1.jpeg',
    alt: 'Bathroom renovation with new vanity and tile work by Orion Remodeling & Handyman',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/b-reno-2.jpeg',
    alt: 'Bathroom remodel featuring updated shower and tile improvements',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/b-reno-3.jpeg',
    alt: 'Bathroom renovation with modern fixtures and improved layout',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/b-reno-4.jpeg',
    alt: 'Bathroom remodel with upgraded sink, mirror, and lighting',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/b-reno-4-2.jpeg',
    alt: 'Bathroom renovation showing new tiling and updated finishes',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/b-reno-5.jpeg',
    alt: 'Bathroom remodel featuring updated flooring and vanity',
    title: 'Bathroom Renovation',
    className: 'aspect-square',
  },
  {
    src: '/f-reno-1.jpeg',
    alt: 'Fence renovation with new wood panels installed by Orion Remodeling & Handyman',
    title: 'Fence Renovation',
    className: 'aspect-square md:aspect-[4/1] md:col-span-3',
  },
  {
    src: '/f-reno-1-2.jpeg',
    alt: 'Wood fence upgrade showing reinforced posts and new boards',
    title: 'Fence Renovation',
    className: 'aspect-square',
  },
  {
    src: '/f-reno-1-3.jpeg',
    alt: 'Fence renovation detail with improved wood slats',
    title: 'Fence Renovation',
    className: 'aspect-square',
  },
  {
    src: '/f-reno-1-4.jpeg',
    alt: 'Completed fence renovation with clean, even wood paneling',
    title: 'Fence Renovation',
    className: 'aspect-square',
  },
  {
    src: '/l-reno-1.jpeg',
    alt: 'Laundry room renovation with new cabinetry and improved shelving',
    title: 'Laundry Room Renovation',
    className: 'aspect-square',
  },
  {
    src: '/lr-reno-1.jpeg',
    alt: 'Living room renovation featuring updated flooring and trim',
    title: 'Living Room Renovation',
    className: 'aspect-square',
  },
  {
    src: '/reno-before-1.jpeg',
    alt: 'Room renovation before image showing original layout and condition',
    title: 'Room Renovation - Before',
    className: 'aspect-square',
  },
  {
    src: '/reno-after-1.jpeg',
    alt: 'Room renovation after image with upgraded finishes and new layout',
    title: 'Room Renovation - After',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-1.jpeg',
    alt: 'Staircase renovation featuring updated wood steps and railing',
    title: 'Staircase Renovation',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-1-2.jpeg',
    alt: 'Staircase remodel showing new treads and refinished railing',
    title: 'Staircase Renovation',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-2-before.jpeg',
    alt: 'Staircase renovation before image showing original condition',
    title: 'Staircase Renovation - Before',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-2.jpeg',
    alt: 'Staircase renovation after image featuring new steps and updated trim',
    title: 'Staircase Renovation - After',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-2-3.jpeg',
    alt: 'Completed staircase renovation with improved finish and design',
    title: 'Staircase Renovation - After',
    className: 'aspect-square',
  },
  {
    src: '/s-reno-3.jpeg',
    alt: 'Staircase remodel with updated railing and modernized steps',
    title: 'Staircase Renovation',
    className: 'aspect-square',
  },
  {
    src: '/renovation.jpeg',
    alt: 'Living room renovation completed by Orion Remodeling & Handyman featuring upgraded flooring and finishes',
    title: 'Living Room Renovation',
    className: 'aspect-[2/1] md:col-span-2',
  },
];
